language: python
python:
  - "3.6"      # current default Python on Travis CI
#  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install codecov
  - pip install pytest-cov
# command to run tests
script:
  - py.test --cov-report xml --cov='./jigglypuffRL/'
  
after_success:
  - codecov
